import { readFileSync } from 'node:fs'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// Active client, selected at build time. No VITE_CLIENT → "swplaces", so existing
// deploys are byte-for-byte unchanged. Mirrors src/config/index.js's default.
const CLIENT = process.env.VITE_CLIENT || 'swplaces'

// Per-client icon set. The files live in branding/<client>/ (favicon.svg + the
// PWA / apple-touch PNGs) and are generated by branding/generate-icons.mjs from
// the client's monogram + primaryColor (swplaces keeps its hand-made "SW" set).
const ICON_FILES = [
  { file: 'favicon.svg', type: 'image/svg+xml' },
  { file: 'apple-touch-icon.png', type: 'image/png' },
  { file: 'icon-192.png', type: 'image/png' },
  { file: 'icon-512.png', type: 'image/png' },
]

// Per-client tab title, apple web-app title, PWA manifest and icons, all driven
// by src/config/<client>.js branding (single source of truth):
// - index.html carries {{APP_TITLE}} / {{APP_APPLE_TITLE}} placeholders replaced
//   here at transform time.
// - manifest.json and the icon files are NOT static: they're generated/selected
//   per client, served by a dev middleware and emitted as build assets.
function clientBrandingPlugin() {
  let branding = null

  async function load() {
    if (branding) return branding
    let mod
    try {
      mod = await import(new URL(`./src/config/${CLIENT}.js`, import.meta.url).href)
    } catch {
      throw new Error(
        `[client-branding] Unknown VITE_CLIENT "${CLIENT}" — no src/config/${CLIENT}.js`
      )
    }
    branding = mod.default.branding
    return branding
  }

  const readIcon = (file) => readFileSync(new URL(`./branding/${CLIENT}/${file}`, import.meta.url))

  const buildManifest = (b) =>
    JSON.stringify(
      {
        name: b.name,
        short_name: b.name,
        description: `${b.name} — dashboard de leads e agenda.`,
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#111111',
        theme_color: b.primaryColor,
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      null,
      2
    )

  return {
    name: 'client-branding',
    async configResolved() {
      await load()
    },
    async transformIndexHtml(html) {
      const b = await load()
      return html
        .replaceAll('{{APP_TITLE}}', b.name)
        .replaceAll('{{APP_APPLE_TITLE}}', b.name)
    },
    configureServer(server) {
      const iconByPath = new Map(ICON_FILES.map((i) => [`/${i.file}`, i]))
      server.middlewares.use(async (req, res, next) => {
        const url = (req.url || '').split('?')[0]
        if (url === '/manifest.json') {
          const b = await load()
          res.setHeader('Content-Type', 'application/manifest+json')
          res.end(buildManifest(b))
          return
        }
        const icon = iconByPath.get(url)
        if (icon) {
          res.setHeader('Content-Type', icon.type)
          res.end(readIcon(icon.file))
          return
        }
        next()
      })
    },
    async generateBundle() {
      const b = await load()
      this.emitFile({ type: 'asset', fileName: 'manifest.json', source: buildManifest(b) })
      for (const { file } of ICON_FILES) {
        this.emitFile({ type: 'asset', fileName: file, source: readIcon(file) })
      }
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), clientBrandingPlugin()],
})
