// Brandon van Riet — client configuration.
// Dashboard + Leads only (no Ana / Conversas). Data comes from Supabase.
// UI language is English via `labels` (keys mirror src/labels.js DEFAULTS; any
// missing key falls back to the Portuguese default). Statuses are English via
// `constants` (separate). Notes STORAGE format is language-independent.
export default {
  key: "brandon",

  labels: {
    // Login
    login_title: "Sign in",
    login_email: "Email",
    login_password: "Password",
    login_submit: "Log in",
    login_submitting: "Logging in...",
    login_error: "Incorrect email or password.",
    // Header / nav
    logout: "Log out",
    logout_title: "Log out",
    // Notifications
    notif_title: "Notifications",
    notif_new_suffix: "new",
    notif_new_leads: "New leads",
    notif_mark_all: "Mark all as seen",
    notif_upcoming: "Upcoming meetings",
    notif_allday: "All day",
    notif_stale_suffix: "not contacted in over 2 days",
    notif_view_all: "View all leads",
    // Dashboard tab
    loading_leads: "Loading leads…",
    stat_total: "Total leads",
    week_suffix: "this week",
    stat_new: "New",
    stat_new_sub: "to contact",
    stat_incontact: "In contact",
    stat_incontact_sub: "in progress",
    stat_closed: "Closed",
    stat_closed_sub: "this month",
    chart_title: "Leads over time",
    chart_sub: "Last 14 days",
    recent_title: "Recent leads",
    view_all: "View all →",
    // Leads tab
    search_label: "Search",
    search_ph: "Name, email, status, notes…",
    f_status: "Status",
    f_classification: "Classification",
    f_budget: "Budget",
    f_intention: "Intent",
    f_source: "Source",
    f_period: "Period",
    f_contact: "Contact",
    f_sort: "Sort",
    all_m: "All",
    all_f: "All",
    unclassified: "Unclassified",
    period_all: "All",
    period_today: "Today",
    period_7d: "Last 7 days",
    period_30d: "Last 30 days",
    contact_all: "All",
    contact_phone: "With phone",
    contact_email: "With email",
    contact_none: "No valid contact",
    sort_recent: "Newest first",
    sort_old: "Oldest first",
    new_lead: "+ New lead",
    empty_leads: "No leads found.",
    // Quick actions / contact buttons
    act_call: "Call",
    act_whatsapp: "WhatsApp",
    act_email: "Email",
    act_instagram: "Instagram",
    no_contact: "No valid contact",
    // Lead drawer
    d_name: "Name",
    d_email: "Email",
    d_phone: "Phone",
    d_budget: "Budget",
    d_intention: "Intent",
    d_status: "Status",
    d_classification: "Classification",
    d_summary: "Summary",
    d_source_post: "Source post",
    d_view_shared: "📷 View shared post ↗",
    d_send_whatsapp: "💬 Send WhatsApp",
    d_delete: "🗑 Delete lead",
    d_deleting: "Deleting…",
    d_delete_confirm: "Are you sure you want to delete this lead?",
    d_delete_failed: "Couldn't delete the lead. Please try again.",
    d_no_name: "No name",
    save_saving: "Saving…",
    save_saved: "Saved ✓",
    save_auto: "Changes are saved automatically.",
    save_failed: "Couldn't save.",
    save_retry: "Try again",
    // Classification
    cls_A: "A — Hot",
    cls_B: "B — Warm",
    cls_C: "C — Cold",
    cls_clear: "Clear",
    // Notes history (display only)
    notes_title: "Notes",
    notes_placeholder: "Write a note…",
    notes_add: "Add note",
    notes_no_date: "no date",
    notes_edited: "edited",
    notes_edit: "Edit",
    notes_delete: "Delete",
    notes_delete_confirm: "Delete this note?",
    notes_save: "Save",
    notes_cancel: "Cancel",
    // New-lead modal
    nl_title: "New lead",
    nl_name: "Name",
    nl_name_ph: "Lead name",
    nl_email: "Email",
    nl_email_ph: "email@example.com",
    nl_phone: "Phone",
    nl_phone_ph: "+351 ...",
    nl_budget: "Budget",
    nl_budget_ph: "e.g. under 300k, 700k-900k",
    nl_intention: "Intent",
    nl_zone: "Area",
    nl_zone_ph: "e.g. Quinta do Lago, Vilamoura",
    nl_notes: "Notes",
    nl_notes_ph: "Useful context about the lead...",
    nl_create: "Create lead",
    nl_creating: "Creating…",
    nl_cancel: "Cancel",
    nl_err_name: "Enter the lead's name.",
    nl_err_contact: "Enter at least one contact (email or phone).",
    nl_err_failed: "Couldn't create the lead. Please try again.",
    nl_intention_opts: ["", "live", "invest", "holiday", "sell", "land", "other"],
    // Follow-ups (Google Calendar)
    fu_title: "Schedule follow-up",
    fu_date: "Date",
    fu_time: "Time",
    fu_note: "Note (optional)",
    fu_note_ph: "e.g. confirm viewing details…",
    fu_confirm: "Schedule follow-up",
    fu_scheduling: "Scheduling…",
    fu_success_prefix: "Follow-up scheduled for",
    fu_error: "Couldn't schedule. Please try again.",
    fu_upcoming_title: "Upcoming follow-ups",
    // Calendar
    cal_prev: "Previous",
    cal_next: "Next",
    cal_updating: "updating…",
    cal_month: "Month",
    cal_week: "Week",
    cal_new_event: "+ New event",
    cal_new_event_short: "+ Event",
    cal_loading: "Loading calendar…",
    cal_not_connected: "Calendar not connected yet.",
    cal_showing_cached: "Showing the previous data.",
    cal_partial: "Some calendars aren't connected:",
    cal_readonly: "Read-only (secondary calendar)",
    cal_untitled: "Untitled",
    cal_untitled_busy: "Busy",
    cal_legend_primary: "Personal",
    cal_legend_secondary: "Work",
    cal_more: "more",
    cal_no_events: "No events on this day.",
    cal_all_day: "All day",
    cal_all_day_suffix: "all day",
    cal_hour: "Hour",
    cal_min: "Min",
    weekdays_short: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    cal_new_title: "New event",
    cal_edit_title: "Edit event",
    cal_view_title: "Event",
    cal_edit: "Edit",
    cal_delete: "Delete",
    cal_f_title: "Title",
    cal_title_ph: "e.g. Viewing with John",
    cal_date: "Date",
    cal_start: "Start",
    cal_duration: "Duration",
    cal_reminder: "Notification",
    cal_location: "Location",
    cal_location_ph: "e.g. Office, Quinta do Lago",
    cal_description: "Description",
    cal_optional: "(optional)",
    cal_title_required: "Title is required.",
    cal_delete_confirm: "Delete this event from the calendar?",
    cal_delete_failed: "Couldn't delete.",
    cal_ends_at_prefix: "ends at",
    cal_ends_on_prefix: "ends",
    cal_rem_none: "No notification",
    cal_rem_hour: "1 hour",
    cal_rem_day: "1 day before",
    cal_rem_hours_suffix: "hours before",
    cal_rem_days_suffix: "days before",
    // Duplicate detection + merge (dedupe feature)
    dup_badge: "Possible duplicate",
    dup_title: "Possible duplicate",
    dup_of: "Same as:",
    dup_matched_phone: "same phone",
    dup_matched_email: "same email",
    dup_primary_hint: "The primary record keeps the status, classification and notes. Nothing is deleted — you can unmerge any time.",
    dup_primary_label: "Primary:",
    dup_switch_primary: "Switch",
    dup_merge: "Merge",
    dup_merging: "Merging…",
    dup_merge_failed: "Couldn't merge. Please try again.",
    merged_badge: "Merged",
    merged_title: "Merged records",
    merged_sources: "Sources",
    merged_answers: "Form answers",
    merged_notes_title: "Notes history",
    merged_note_primary: "primary",
    merged_unmerge: "Unmerge",
    merged_unmerging: "Unmerging…",
    merged_unmerge_confirm: "Unmerge this record? It will reappear as a separate lead.",
    merged_unmerge_failed: "Couldn't unmerge.",
    // Dates
    date_locale: "en-GB",
    today: "Today",
    yesterday: "Yesterday",
    days_ago_suffix: "ago",
    months_short: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  },

  branding: {
    name: "Brandon van Riet",
    logoText: "Brandon van Riet",
    logoMonogram: "B",
    tagline: "Algarve",
    primaryColor: "#C9A96E",     // same gold as SW Places for now
    loginPlaceholder: "email@brandonvanriet.com",
    emailProvider: "system",     // "system" → mailto: (until Brandon says otherwise)
  },

  users: [
    { email: "daniel.silva20@hotmail.com", password: "daniel2026", role: "admin", name: "Daniel" },
    { email: "brandon@brandonvanriet.com", password: "brandon2026", role: "admin", name: "Brandon" },
  ],

  features: {
    dashboard: true,
    leads: true,
    conversas: false,
    recuperar: false,
    newsletter: false,
    ana: false,
    calendar: true,     // Google Calendar (month/week views + events) via GOOGLE_CALENDAR_ID
    followups: true,    // "Schedule follow-up" on leads (Google Calendar, api/follow-ups.js)
    dedupe: true,       // duplicate-lead detection + link-based merge (api/lead-links.js)
  },

  // Brandon's own pipeline (English). STATUS_CONFIG reuses the SW Places colour
  // styles: New→"Novo" blue, Contacted→"Contactado" amber, Viewing booked→
  // "Reunião agendada" violet, Closed→"Fechado" green, Lost→"Perdido" rose.
  constants: {
    STATUS_CONFIG: {
      "New":                  { bg: "#EFF6FF", text: "#1D4ED8", dot: "#3B82F6", border: "#BFDBFE" },
      "Contacted — no answer": { bg: "#FFFBEB", text: "#92400E", dot: "#F59E0B", border: "#FDE68A" }, // amber / warning
      "Contacted — answered":  { bg: "#F0FDFA", text: "#0F766E", dot: "#14B8A6", border: "#99F6E4" }, // teal / positive
      "Viewing booked":       { bg: "#F5F3FF", text: "#5B21B6", dot: "#8B5CF6", border: "#DDD6FE" },
      "Closed":               { bg: "#F0FDF4", text: "#14532D", dot: "#22C55E", border: "#BBF7D0" },
      "Lost":                 { bg: "#FFF1F2", text: "#881337", dot: "#F43F5E", border: "#FECDD3" },
    },
    STATUSES: ["New", "Contacted — no answer", "Contacted — answered", "Viewing booked", "Closed", "Lost"],
    // First entry is the "show all" sentinel the shared LeadsTab filter expects
    // (it defaults filterBudget/filterIntention to "Todos"/"Todas"); the real
    // options follow. Prepended to keep the filter dropdowns functional.
    BUDGETS: ["Todos", "Under €1M", "€1M – €2M", "€2M – €5M", "Over €5M"],
    INTENTIONS: ["Todas", "A primary residence", "A second home / holiday property", "An investment / rental property"],
    // The status whose selection opens the calendar meeting-scheduling flow
    // (calendar is enabled for Brandon — features.calendar true).
    calendarTriggerStatus: "Viewing booked",
    // Statuses counted by the Dashboard "Em contacto" (in progress) stat.
    inContactStatuses: ["Contacted — no answer", "Contacted — answered", "Viewing booked"],
    // Named statuses used by dashboard logic. noAnswer null → Brandon has no
    // "no answer" status, so the WhatsApp "no answer" button never shows.
    statusRoles: { new: "New", closed: "Closed", noAnswer: null },
  },

  dataSource: "supabase",
};
